### ISSUE TITLE
Regarding the issue of metrics calculation

### ISSUE THREAD

**Issue by wwangcece** [huai-chang/VQIR#1]
Hello, thank you very much for your excellent work. I noticed that there seems to be some discrepancy in the sizes of the reconstructed images compared to the original HR images. How do you calculate the metrics in this case?

**Comment by huai-chang** [comment]
> Hello, thank you very much for your excellent work. I noticed that there seems to be some discrepancy in the sizes of the reconstructed images compared to the original HR images. How do you calculate the metrics in this case?

During the inference process, we use a cropping operation to ensure the length and width of the input image are multiples of the scaling factor (16 or 32).
```
# In VQIR/vqir/data/LRHR_dataset.py and VQIR/vqir/data/MultiHR_dataset.py
# modcrop in the validation / test phase
if self.opt['phase'] != 'train':
    img_HR = util.modcrop(img_HR, scale)
```
To calculate the metrics, you can manually crop the input images before inference or add the following code to VQIR/vqir/models/vqir_model.py or VQIR/vqir/models/vqirrf_model.py.
```
if self.opt['val']['suffix']:
    save_hr_path = osp.join(self.opt['path']['results_root'], dataset_name, 'HR', f'{img_name}_{self.opt["val"]["suffix"]}.png')
else:
    save_hr_path = osp.join(self.opt['path']['results_root'], dataset_name, 'HR', f'{img_name}.png')
util.imwrite(hr_img, save_hr_path)
```
This will save the cropped HR image.

**Comment by wwangcece** [comment]
Got it. Thanks for your reply!
